// Forge System Architecture Data

export interface ArchitectureNode {
  id: string;
  label: string;
  type: 'frontend' | 'api' | 'agent' | 'database' | 'external';
  description: string;
  features: string[];
  tech: string[];
  files?: string[];
  icon: string;
  position: { x: number; y: number };
}

export interface ArchitectureEdge {
  id: string;
  source: string;
  target: string;
  label?: string;
  animated?: boolean;
  style?: React.CSSProperties;
}

export interface Workflow {
  id: string;
  name: string;
  description: string;
  nodeIds: string[];
  edgeIds: string[];
  color: string;
}

export const architectureNodes: ArchitectureNode[] = [
  // FRONTEND LAYER
  {
    id: 'dashboard',
    label: 'Dashboard',
    type: 'frontend',
    description: 'Main content hub showing all projects, analytics, and quick actions',
    features: [
      'Project list with search/filter',
      'Recent projects',
      'Quick create actions',
      'SEO score overview',
    ],
    tech: ['Next.js 14', 'React 19', 'Shadcn UI'],
    files: ['app/dashboard/page.tsx', 'components/dashboard/*'],
    icon: 'LayoutDashboard',
    position: { x: 50, y: 100 },
  },
  {
    id: 'editor',
    label: 'Content Editor',
    type: 'frontend',
    description: 'Rich text editor with SEO Assistant, live keyword tracking, and export tools',
    features: [
      'TipTap rich text editing',
      'Real-time SEO scoring',
      'Live keyword density',
      'CMS-ready export',
      'Auto-save functionality',
    ],
    tech: ['TipTap', 'React', 'TailwindCSS'],
    files: ['components/editor/RichTextEditor.tsx', 'components/editor/SEOAssistant.tsx'],
    icon: 'FileEdit',
    position: { x: 50, y: 300 },
  },
  {
    id: 'smartbriefs',
    label: 'SmartBrief Builder',
    type: 'frontend',
    description: 'AI-powered content template system with URL analysis and pattern learning',
    features: [
      'Visual template editor',
      'AI URL analysis',
      'Structure learning',
      'Reusable templates',
      'Share/private modes',
    ],
    tech: ['React', 'TipTap', 'Claude AI'],
    files: ['app/smartbriefs/page.tsx', 'components/modals/BriefModal.tsx'],
    icon: 'FileText',
    position: { x: 50, y: 500 },
  },
  {
    id: 'writer-factory',
    label: 'Writer Factory',
    type: 'frontend',
    description: 'Train custom AI writer models by uploading example articles',
    features: [
      'Article upload/paste',
      'Style analysis',
      'Model training progress',
      'Voice customization',
      'Training content management',
    ],
    tech: ['React', 'OpenAI Embeddings', 'pgvector'],
    files: ['app/writer-factory/page.tsx', 'components/dashboard/WriterFactoryPanel.tsx'],
    icon: 'Brain',
    position: { x: 50, y: 700 },
  },
  {
    id: 'research-center',
    label: 'Research Center',
    type: 'frontend',
    description: 'News search, fact verification, and source trust management',
    features: [
      'Tavily news search',
      'Article trust scoring',
      'Fact verification',
      'Source feedback',
      'Research brief generation',
    ],
    tech: ['React', 'Tavily AI', 'Claude AI'],
    files: ['components/dashboard/ResearchPanel.tsx'],
    icon: 'Search',
    position: { x: 50, y: 1100 },
  },
  {
    id: 'admin-panel',
    label: 'Admin Panel',
    type: 'frontend',
    description: 'System administration, user management, and AI configuration',
    features: [
      'User management',
      'API key management',
      'AI Tuner (master instructions)',
      'Agent Tuner (8 agents)',
      'SSO configuration',
      'Trusted sources',
    ],
    tech: ['React', 'Supabase Admin'],
    files: ['app/admin/page.tsx', 'components/admin/*'],
    icon: 'Settings',
    position: { x: 50, y: 1300 },
  },
  {
    id: 'ai-helper',
    label: 'AI Helper Bot',
    type: 'frontend',
    description: 'Contextual AI assistant with knowledge base and web search',
    features: [
      'Chat interface',
      'Q&A knowledge base',
      'Web search integration',
      'Admin-curated answers',
      'Context-aware help',
    ],
    tech: ['React', 'Claude AI', 'Perplexity API'],
    files: ['components/ai/AIAssistant.tsx'],
    icon: 'Bot',
    position: { x: 50, y: 1500 },
  },

  // API LAYER
  {
    id: 'api-generate',
    label: '/api/generate',
    type: 'api',
    description: 'Content generation endpoint - orchestrates Writer Training and Content Generation agents',
    features: [
      'RAG-based generation',
      'Writer voice matching',
      'SEO compliance',
      'Streaming responses',
    ],
    tech: ['Next.js API Route', 'Claude AI'],
    files: ['app/api/generate/route.ts'],
    icon: 'Zap',
    position: { x: 400, y: 100 },
  },
  {
    id: 'api-research',
    label: '/api/research/*',
    type: 'api',
    description: 'Research pipeline, news search, and fact verification',
    features: [
      '/research/pipeline - SSE research orchestration (Tavily → QA → Fact Verify → SEO keywords)',
      '/research/story - Tavily search',
      '/research/verify-facts - Fact checking',
      'Trust score calculation',
    ],
    tech: ['Next.js API', 'Tavily AI'],
    files: ['app/api/research/*'],
    icon: 'Database',
    position: { x: 400, y: 300 },
  },
  {
    id: 'api-seo',
    label: '/api/seo/*',
    type: 'api',
    description: 'SEO analysis, suggestions, and optimization endpoints',
    features: [
      '/seo/analyze - Score calculation',
      '/seo/suggestions - AI recommendations',
      '/seo/auto-optimize - Content enhancement',
      '/seo/internal-links - Link suggestions',
      '/seo/analyze-package - Full analysis',
    ],
    tech: ['Next.js API', 'Claude AI'],
    files: ['app/api/seo/*'],
    icon: 'TrendingUp',
    position: { x: 400, y: 500 },
  },
  {
    id: 'api-train',
    label: '/api/writer-models/train',
    type: 'api',
    description: 'Writer model training - style analysis and embedding creation',
    features: [
      'Style analysis',
      'Embedding generation',
      'Pattern extraction',
      'Voice characterization',
    ],
    tech: ['Next.js API', 'OpenAI Embeddings'],
    files: ['app/api/writer-models/train/route.ts'],
    icon: 'Cpu',
    position: { x: 400, y: 700 },
  },
  {
    id: 'api-briefs',
    label: '/api/briefs/analyze-urls',
    type: 'api',
    description: 'SmartBrief URL analysis - learns structure from example articles',
    features: [
      'URL content extraction',
      'Structure analysis',
      'Pattern recognition',
      'Template generation',
    ],
    tech: ['Next.js API', 'Claude AI'],
    files: ['app/api/briefs/analyze-urls/route.ts'],
    icon: 'Link',
    position: { x: 400, y: 900 },
  },
  {
    id: 'api-assistant',
    label: '/api/assistant/chat',
    type: 'api',
    description: 'AI Helper Bot chat endpoint with knowledge base search',
    features: [
      'Conversational AI',
      'Knowledge base RAG',
      'Web search fallback',
      'Context retention',
    ],
    tech: ['Next.js API', 'Claude AI', 'Perplexity'],
    files: ['app/api/assistant/chat/route.ts'],
    icon: 'MessageSquare',
    position: { x: 400, y: 1300 },
  },
  {
    id: 'api-admin',
    label: '/api/admin/*',
    type: 'api',
    description: 'Admin endpoints for user, API key, and agent management',
    features: [
      '/admin/users - User CRUD',
      '/admin/api-keys - Key management',
      '/admin/agents - Agent configuration',
    ],
    tech: ['Next.js API', 'Supabase Admin'],
    files: ['app/api/admin/*'],
    icon: 'Shield',
    position: { x: 400, y: 1500 },
  },
  {
    id: 'api-auth',
    label: '/api/auth/*',
    type: 'api',
    description: 'Authentication endpoints including Microsoft SSO',
    features: [
      '/auth/callback - OAuth callback',
      '/auth/signout - Session cleanup',
      'Microsoft Azure AD integration',
    ],
    tech: ['Next.js API', 'Supabase Auth', 'Azure AD'],
    files: ['app/api/auth/*'],
    icon: 'Lock',
    position: { x: 400, y: 1700 },
  },

  // MULTI-AGENT AI SYSTEM
  {
    id: 'agent-content',
    label: 'Content Generation Agent',
    type: 'agent',
    description: 'Generates articles in authentic writer voice using RAG',
    features: [
      'RAG-based generation',
      'Writer voice matching',
      'SEO integration',
      'Streaming output',
      'Configurable temperature/tokens',
    ],
    tech: ['Claude Sonnet 4', 'pgvector', 'RAG'],
    files: ['lib/agents/content-generation.ts'],
    icon: 'Sparkles',
    position: { x: 750, y: 100 },
  },
  {
    id: 'agent-training',
    label: 'Writer Training Agent',
    type: 'agent',
    description: 'Analyzes writing style and creates embeddings',
    features: [
      'Style pattern analysis',
      'Tone/voice extraction',
      'Embedding generation',
      'Training data curation',
    ],
    tech: ['Claude AI', 'OpenAI Embeddings'],
    files: ['lib/agents/writer-training.ts'],
    icon: 'GraduationCap',
    position: { x: 750, y: 300 },
  },
  {
    id: 'agent-seo',
    label: 'SEO Optimization Agent',
    type: 'agent',
    description: 'Keyword optimization and content enhancement',
    features: [
      'Keyword density optimization',
      'Heading structure suggestions',
      'Meta description generation',
      'Content enhancement',
    ],
    tech: ['Claude AI', 'SEO algorithms'],
    files: ['lib/agents/seo-optimization.ts'],
    icon: 'Target',
    position: { x: 750, y: 500 },
  },
  {
    id: 'agent-qa',
    label: 'Quality Assurance Agent',
    type: 'agent',
    description: 'Grammar and spell checking integration',
    features: [
      'Grammar validation',
      'Spell checking',
      'Style consistency',
      'LanguageTool integration',
    ],
    tech: ['LanguageTool API', 'Claude AI'],
    files: ['lib/agents/quality-assurance.ts'],
    icon: 'CheckCircle',
    position: { x: 750, y: 700 },
  },
  {
    id: 'agent-persona',
    label: 'Persona & Tone Agent',
    type: 'agent',
    description: 'Adapts content voice and personality',
    features: [
      'Tone adjustment',
      'Voice adaptation',
      'Personality matching',
      'Style consistency',
    ],
    tech: ['Claude AI'],
    files: ['lib/agents/persona-tone.ts'],
    icon: 'Users',
    position: { x: 750, y: 900 },
  },
  {
    id: 'agent-research-orchestrator',
    label: 'Research Orchestrator Agent',
    type: 'agent',
    description: 'Runs the research pipeline: Tavily search, relevance evaluation, fact verification, keyword suggestions',
    features: [
      'Tavily search & relevance filtering',
      'Fact verification loop (with follow-up)',
      'SEO keyword suggestions',
      'SSE progress streaming',
    ],
    tech: ['Claude AI', 'Tavily AI'],
    files: ['lib/agents/research-orchestrator.ts'],
    icon: 'Search',
    position: { x: 750, y: 1100 },
  },
  {
    id: 'agent-visual',
    label: 'Visual Extraction Agent',
    type: 'agent',
    description: 'Parses images and screenshots for data extraction',
    features: [
      'Image analysis',
      'OCR & table extraction',
      'Multi-image processing',
      'Claude Vision + GPT-4o fallback',
    ],
    tech: ['Claude Vision', 'GPT-4o Vision'],
    files: ['lib/agents/visual-extraction.ts'],
    icon: 'Eye',
    position: { x: 750, y: 1300 },
  },
  {
    id: 'agent-fact',
    label: 'Fact Verification Agent',
    type: 'agent',
    description: 'Cross-references facts across multiple sources',
    features: [
      'Multi-source verification',
      'Confidence scoring',
      'Disputed fact detection',
      'Source credibility analysis',
    ],
    tech: ['Claude AI', 'Tavily AI'],
    files: ['lib/agents/fact-verification.ts'],
    icon: 'ShieldCheck',
    position: { x: 750, y: 1500 },
  },

  // DATABASE LAYER
  {
    id: 'db-users',
    label: 'users',
    type: 'database',
    description: 'User profiles with roles and authentication',
    features: [
      'User profiles',
      'Role management (admin, strategist, editor)',
      'Azure AD integration',
      'Account status tracking',
    ],
    tech: ['PostgreSQL', 'Supabase', 'RLS'],
    files: ['supabase/migrations/00001_initial_schema.sql'],
    icon: 'Users',
    position: { x: 1100, y: 100 },
  },
  {
    id: 'db-projects',
    label: 'projects',
    type: 'database',
    description: 'Content projects with metadata and research',
    features: [
      'Project metadata',
      'Content storage (TipTap JSON)',
      'SEO scores',
      'Research briefs',
      'File name tracking',
    ],
    tech: ['PostgreSQL', 'JSONB'],
    files: ['supabase/migrations/00001_initial_schema.sql'],
    icon: 'FolderOpen',
    position: { x: 1100, y: 300 },
  },
  {
    id: 'db-models',
    label: 'writer_models',
    type: 'database',
    description: 'AI writer model configurations',
    features: [
      'Model metadata',
      'Strategist assignment',
      'Training piece count',
      'Model descriptions',
    ],
    tech: ['PostgreSQL', 'JSONB'],
    files: ['supabase/migrations/00001_initial_schema.sql'],
    icon: 'Brain',
    position: { x: 1100, y: 500 },
  },
  {
    id: 'db-training',
    label: 'training_content',
    type: 'database',
    description: 'Training articles with vector embeddings',
    features: [
      'Article content',
      'Vector embeddings (1536 dimensions)',
      'Style analysis metadata',
      'RAG similarity search',
    ],
    tech: ['PostgreSQL', 'pgvector', 'OpenAI Embeddings'],
    files: ['supabase/migrations/00001_initial_schema.sql'],
    icon: 'Database',
    position: { x: 1100, y: 700 },
  },
  {
    id: 'db-briefs',
    label: 'briefs',
    type: 'database',
    description: 'SmartBrief templates with SEO config',
    features: [
      'Template content (TipTap JSON)',
      'SEO configuration',
      'Share/private modes',
      'Category organization',
    ],
    tech: ['PostgreSQL', 'JSONB'],
    files: ['supabase/migrations/00001_initial_schema.sql'],
    icon: 'FileText',
    position: { x: 1100, y: 900 },
  },
  {
    id: 'db-api-keys',
    label: 'api_keys',
    type: 'database',
    description: 'Encrypted API credentials for external services',
    features: [
      'Encrypted storage',
      'Service name mapping',
      'Admin-only access',
      'Update tracking',
    ],
    tech: ['PostgreSQL', 'Encryption'],
    files: ['supabase/migrations/00001_initial_schema.sql'],
    icon: 'Key',
    position: { x: 1100, y: 1100 },
  },
  {
    id: 'db-ai-settings',
    label: 'ai_settings',
    type: 'database',
    description: 'AI agent configurations and master instructions',
    features: [
      'Agent parameters (temperature, tokens)',
      'Master instructions',
      'Model selection',
      'Enable/disable flags',
    ],
    tech: ['PostgreSQL'],
    files: ['supabase/migrations/00001_initial_schema.sql'],
    icon: 'Settings',
    position: { x: 1100, y: 1300 },
  },
  {
    id: 'db-trusted-sources',
    label: 'trusted_sources',
    type: 'database',
    description: 'Curated list of trusted news sources with ratings',
    features: [
      'Domain management',
      'Trust level scoring',
      'Category tagging',
      'Admin notes',
    ],
    tech: ['PostgreSQL'],
    files: ['supabase/migrations/00008_trusted_sources.sql'],
    icon: 'Shield',
    position: { x: 1100, y: 1500 },
  },
  {
    id: 'db-helper',
    label: 'ai_helper_entries',
    type: 'database',
    description: 'Knowledge base for AI Helper Bot',
    features: [
      'Q&A pairs',
      'Tag-based search',
      'Active/inactive toggle',
      'Admin curation',
    ],
    tech: ['PostgreSQL', 'Full-text search'],
    files: ['supabase/migrations/00006_ai_helper.sql'],
    icon: 'BookOpen',
    position: { x: 1100, y: 1700 },
  },

  // EXTERNAL SERVICES
  {
    id: 'ext-claude',
    label: 'Anthropic Claude',
    type: 'external',
    description: 'Primary AI engine - Claude Sonnet 4',
    features: [
      'Content generation',
      'Style analysis',
      'Vision processing',
      'All 7 AI agents',
    ],
    tech: ['Claude Sonnet 4', 'Anthropic API'],
    icon: 'Bot',
    position: { x: 1450, y: 300 },
  },
  {
    id: 'ext-openai',
    label: 'OpenAI',
    type: 'external',
    description: 'Embeddings and GPT-4o Vision fallback',
    features: [
      'text-embedding-3-small (1536d)',
      'GPT-4o Vision fallback',
      'Embedding generation',
    ],
    tech: ['OpenAI API', 'GPT-4o'],
    icon: 'Sparkles',
    position: { x: 1450, y: 600 },
  },
  {
    id: 'ext-tavily',
    label: 'Tavily AI',
    type: 'external',
    description: 'News search engine for research',
    features: [
      'Real-time news search',
      'Advanced search depth',
      'Content extraction',
      'Relevance scoring',
    ],
    tech: ['Tavily API'],
    icon: 'Newspaper',
    position: { x: 1450, y: 900 },
  },
  {
    id: 'ext-languagetool',
    label: 'LanguageTool',
    type: 'external',
    description: 'Grammar and spell checking service',
    features: [
      'Grammar validation',
      'Spell checking',
      'Style suggestions',
      'Multi-language support',
    ],
    tech: ['LanguageTool API'],
    icon: 'SpellCheck',
    position: { x: 1450, y: 1200 },
  },
  {
    id: 'ext-azure',
    label: 'Microsoft Azure AD',
    type: 'external',
    description: 'Single Sign-On authentication',
    features: [
      'OAuth 2.0',
      'Enterprise SSO',
      'Tenant management',
      'User provisioning',
    ],
    tech: ['Azure AD', 'OAuth'],
    icon: 'Cloud',
    position: { x: 1450, y: 1500 },
  },
  {
    id: 'ext-supabase-auth',
    label: 'Supabase Auth',
    type: 'external',
    description: 'Session and authentication management',
    features: [
      'Session management',
      'OAuth integration',
      'JWT tokens',
      'Row-level security',
    ],
    tech: ['Supabase', 'PostgreSQL'],
    icon: 'Lock',
    position: { x: 1450, y: 1700 },
  },
];

export const architectureEdges: ArchitectureEdge[] = [
  // Frontend → API
  { id: 'e-dash-gen', source: 'dashboard', target: 'api-generate', label: 'Create Project' },
  { id: 'e-edit-gen', source: 'editor', target: 'api-generate', label: 'Generate Content' },
  { id: 'e-edit-seo', source: 'editor', target: 'api-seo', label: 'Analyze SEO' },
  { id: 'e-brief-api', source: 'smartbriefs', target: 'api-briefs', label: 'Analyze URLs' },
  { id: 'e-writer-train', source: 'writer-factory', target: 'api-train', label: 'Train Model' },
  { id: 'e-research-api', source: 'research-center', target: 'api-research', label: 'Search News' },
  { id: 'e-admin-api', source: 'admin-panel', target: 'api-admin', label: 'Manage' },
  { id: 'e-helper-api', source: 'ai-helper', target: 'api-assistant', label: 'Chat' },

  // API → Agents
  { id: 'e-gen-content', source: 'api-generate', target: 'agent-content', label: 'Generate' },
  { id: 'e-gen-training', source: 'api-generate', target: 'agent-training', label: 'Get Style' },
  { id: 'e-seo-agent', source: 'api-seo', target: 'agent-seo', label: 'Optimize' },
  { id: 'e-train-agent', source: 'api-train', target: 'agent-training', label: 'Analyze' },
  { id: 'e-research-fact', source: 'api-research', target: 'agent-fact', label: 'Verify' },

  // Agents → External Services
  { id: 'e-content-claude', source: 'agent-content', target: 'ext-claude' },
  { id: 'e-training-claude', source: 'agent-training', target: 'ext-claude' },
  { id: 'e-training-openai', source: 'agent-training', target: 'ext-openai', label: 'Embeddings' },
  { id: 'e-seo-claude', source: 'agent-seo', target: 'ext-claude' },
  { id: 'e-qa-lang', source: 'agent-qa', target: 'ext-languagetool' },
  { id: 'e-persona-claude', source: 'agent-persona', target: 'ext-claude' },
  { id: 'e-creative-claude', source: 'agent-creative', target: 'ext-claude' },
  { id: 'e-visual-claude', source: 'agent-visual', target: 'ext-claude', label: 'Vision' },
  { id: 'e-visual-openai', source: 'agent-visual', target: 'ext-openai', label: 'Fallback' },
  { id: 'e-fact-claude', source: 'agent-fact', target: 'ext-claude' },
  { id: 'e-research-tavily', source: 'api-research', target: 'ext-tavily', label: 'Search' },
  { id: 'e-auth-azure', source: 'api-auth', target: 'ext-azure', label: 'SSO' },
  { id: 'e-auth-supabase', source: 'api-auth', target: 'ext-supabase-auth' },

  // API → Database
  { id: 'e-api-users', source: 'api-admin', target: 'db-users' },
  { id: 'e-gen-projects', source: 'api-generate', target: 'db-projects' },
  { id: 'e-gen-models', source: 'api-generate', target: 'db-models' },
  { id: 'e-train-training', source: 'api-train', target: 'db-training' },
  { id: 'e-brief-db', source: 'api-briefs', target: 'db-briefs' },
  { id: 'e-admin-keys', source: 'api-admin', target: 'db-api-keys' },
  { id: 'e-admin-settings', source: 'api-admin', target: 'db-ai-settings' },
  { id: 'e-research-sources', source: 'api-research', target: 'db-trusted-sources' },
  { id: 'e-assistant-helper', source: 'api-assistant', target: 'db-helper' },

  // Agent → Database (RAG)
  { id: 'e-content-training', source: 'agent-content', target: 'db-training', label: 'RAG Search', animated: true },
];

export const workflows: Workflow[] = [
  {
    id: 'article-generation',
    name: 'Article Generation',
    description: 'Complete workflow from project creation to published article',
    nodeIds: [
      'dashboard',
      'editor',
      'api-generate',
      'agent-content',
      'agent-training',
      'ext-claude',
      'db-training',
      'db-models',
      'db-projects',
    ],
    edgeIds: ['e-edit-gen', 'e-gen-content', 'e-gen-training', 'e-content-claude', 'e-content-training'],
    color: '#8b5cf6',
  },
  {
    id: 'writer-training',
    name: 'Writer Model Training',
    description: 'Upload articles and train custom AI writer models',
    nodeIds: [
      'writer-factory',
      'api-train',
      'agent-training',
      'ext-claude',
      'ext-openai',
      'db-training',
      'db-models',
    ],
    edgeIds: ['e-writer-train', 'e-train-agent', 'e-training-claude', 'e-training-openai', 'e-train-training'],
    color: '#10b981',
  },
  {
    id: 'seo-optimization',
    name: 'SEO Optimization',
    description: 'Real-time SEO analysis and content optimization',
    nodeIds: [
      'editor',
      'api-seo',
      'agent-seo',
      'ext-claude',
      'db-projects',
    ],
    edgeIds: ['e-edit-seo', 'e-seo-agent', 'e-seo-claude'],
    color: '#06b6d4',
  },
  {
    id: 'research',
    name: 'Research & Fact Verification',
    description: 'News search with trust scoring and fact checking',
    nodeIds: [
      'research-center',
      'api-research',
      'agent-fact',
      'ext-tavily',
      'ext-claude',
      'db-trusted-sources',
      'db-projects',
    ],
    edgeIds: ['e-research-api', 'e-research-tavily', 'e-research-fact', 'e-fact-claude', 'e-research-sources'],
    color: '#ec4899',
  },
];
